### ISSUE TITLE
Is this repo still alive?

### ISSUE THREAD

**Issue by brotkiste** [MazeMap/Leaflet.TileLayer.PouchDBCached#38]
@MazeMap @nikolauskrismer @svenpanko

Which fork/repo should I depend on for other projects? Are there any plans to merge the PRs for PouchDB 6.0.0 + in this repo?

**Comment by intuitiveminds** [comment]
@brotkiste I don't use my implementation anymore because of various problems on mobile devices (that's what I needed it for), most notably size constraints

**Comment by brotkiste** [comment]
By size you mean cache size? what do you use instead? :)

**Comment by intuitiveminds** [comment]
The implementation uses the default adapter for PouchDB on mobile devices, which is either IndexedDb or WebSql. In my case (iOS and PouchDB 6.3) it defaults to WebSql and has a size limit of 50 MB max. Since the tiles I intended to cache need around 120 MB, this wasn't feasible. I could change it to SQLite, but that would impact the performance, so I now fall back to the browser cache (I only wanted to cache tiles of the highest zoom level), which works fine in my case.

If I were to adapt this cache, I think I would use a filesystem cache (again, on mobile)

**Comment by brotkiste** [comment]
Ah ok, thanks a lot

**Comment by brotkiste** [comment]
I'm now using service workers to cache the tiles, works perfectly

**Comment by dagjomar** [comment]
This repo is not being maintained. I suggest you clone it work from there :)

**Comment by nikolauskrismer** [comment]
Sorry for the late answer... but I hope that late is better than never.
I do maintain my forked repo. However, I am not really happy with the project.
Updates seem to be very problematic with both, leaflet and PouchDB.

I managed to get PouchDB 7.0.0 working, but still have not had the time to look into upgrading leaflet to 1.3.2 or the just released 1.3.3. Both leaflet versions cause problems, so the last version of leaflet that works without problems is 1.3.1 (I noted that in my package.json file right now, since I tested it today).

So you are very welcome to use my forked repo :-)
If you have the time to look into the update to leaflet 1.3.3 I'd really appreciate a PR and would happily merge changes :-)

EDIT: I found the problem with upgrading to latest leaflet:
https://github.com/nikolauskrismer/Leaflet.TileLayer.PouchDBCached/issues/2
